### PR TITLE
touch

### PR DESCRIPTION
**Pull request by kim-em**
* [ ] Put an X in this bracket to confirm you have read the
  [External Contribution Guidelines](https://github.com/leanprover/lean4/blob/master/doc/contributions.md).

* Please put the link to your `RFC` or `bug` issue here.
  PRs missing this link will be marked as `missing RFC`.

* If that issue does not already have approval from a developer,
  please be sure to open this PR in "Draft" mode.

* Please make sure the PR has excellent documentation and tests.
  If we label it `missing documentation` or `missing tests` then it needs fixing!

### CODE REVIEW

**Comment by kim-em** [comment]
Checking to see if labelling from comments works.

awaiting-review

**Comment by kim-em** [comment]
awaiting-author

**Comment by kim-em** [comment]
WIP

**Comment by kim-em** [comment]
awaiting-review

**Comment by kim-em** [comment]
awaiting-author

**Comment by kim-em** [comment]
WIP

**Comment by kim-em** [comment]
WIP

**Comment by kim-em** [comment]
WIP

**Comment by kim-em** [comment]
awaiting-review

**Comment by kim-em** [comment]
WIP

**Comment by kim-em** [comment]
awaiting-review

**Comment by semorrison** [comment]
awaiting-review

**Pull request merged**
